version: "3.0"
services:
  db:
    image: mysql:5.7.19
    environment:
      - MSQL_DATABASE=loja
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /home/bruno/Documentos/alura/kubernetes/Projeto/volume_mysql:/var/lib/mysql