apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: aplicacao-pod
  name: aplicacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aplicacao-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: aplicacao-pod
    spec:
      containers:
        - name: container-aplicacao-loja
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80